### ISSUE TITLE
Feature request: Trigger on button release, assign multiple keys

### ISSUE THREAD

**Issue by aaaaaammmmmm** [roc7890/RadialMenu#2]
Hi, thanks for this app, I have looked for something like this for Macos for a long time, so I just purchased a licence in the App Store. 
My first feature request would be the ability to trigger the shortcuts on keyboard button release. That way you could hold down the trigger key, move the mouse and release the trigger key to trigger the shortcut. This allows for very fast triggering of the shortcuts once you learn them. 
I have tried to make a demo[ in this video ](https://www.youtube.com/watch?v=h1skDTkWRrA) using this [Windows tool from dumbeau](https://github.com/dumbeau/AutoHotPie)

Another feature request would be to be able to make multiple menus on different keys. This would make it possible to assign a large number of shortcuts for tasks like video editing ect.

**Comment by roc7890** [comment]
Thank you very much for your detailed and specific suggestions. The first presentation is very clear, and there are no doubts. We can start working on it soon.

For the second one, I just need a little clarification. Are you referring to using different trigger methods to activate different menus within the same application? For example, a specific example would be: Pressing cmd + a in Safari triggers menu group A, and pressing cmd + b in Safari triggers a different menu group B, correct?

**Comment by aaaaaammmmmm** [comment]
Thank you for your fast reply!
Yes, you are correct about the second one. 
For example, for video editing, I could have all my Timeline Tools on "T" and all my audio tools on "A" ect.

**Comment by roc7890** [comment]
OK,Thanks. We will work out them in recent versions.
