### ISSUE TITLE
Please hide the menu if trigger key is pressed once again

### ISSUE THREAD

**Issue by mutleybg** [roc7890/RadialMenu#3]
Hi,

I like your app very much and purchased it almost immediately.
I have one request. Sometimes I accidentally trigger the menu by pressing Cmd and I would like to close it immediately with the same key. So, if possible when the menu is opened and you hit again the trigger key close the menu.

Best regards

**Comment by roc7890** [comment]
OK，i'll add an option for this in recent versions . Sorry for responsing   so late .

**Comment by roc7890** [comment]
support in 2.1.1
