### ISSUE TITLE
Cannot open app or a file

### ISSUE THREAD

**Issue by mutleybg** [roc7890/RadialMenu#7]
I bought the app couple of months ago and I like it. However, since the last version(I think) I cannot open any app or a file. Every time I have the error:
<img width="262" alt="image" src="https://github.com/user-attachments/assets/1160c978-5b0a-43ff-8d89-b16a06ced434">
The files/apps have the same permissions (I can open them with the user I'm logged in).
I don't know how to delete the menu. Could you explain to me or point me to a documentation (I also didn't find such)?
Or do I have to give permission to CirMenu somewhere in System Settings?

**Comment by roc7890** [comment]
Dose new created menu item work ? If the new one works , then you need to set those old menu items once again.  For safety reason Sandbox App can not  open files /Apps directly , unless users have open them in file dialog first. Try to set those menu items again. The cache permission data may has been lost for some unknown issue.

**Comment by mutleybg** [comment]
After recreation of menu items and restart it works
